version: '3.7'
services:

  database:
    build: ./database
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  
  api:
    build: ./api
    depends_on:
      - database
    ports: 
      - '8080:8080'